version: "3.8"
services:
  db:
    image: postgres:12.2
    restart: always
    environment:
      POSTGRES_USER: store_user
      POSTGRES_PASSWORD: store_password
    ports:
      - "5433:5432"
    expose:
      - "5433"