name: Continuous Integration

on:
  push:
    branches-ignore:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_USER: store_user
          POSTGRES_PASSWORD: store_password
          POSTGRES_DB: store_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      MIX_ENV: test
      DB_PORT: 5432
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup elixir
        uses: actions/setup-elixir@v1
        with:
          otp-version: '24'
          elixir-version: '1.12.3-otp-24'
          experimental-otp: true
      
      - name: Install Dependencies
        run: mix deps.get

      - name: Format
        run: mix format --check-formatted

      - name: Credo
        run: mix credo --strict
        
      - name: Test
        run: mix test
          